In [ ]:
Numpy has 270 functions in total

## 1. Array creation function

In [2]:
import numpy as np

In [4]:
#crete an array from a list
a = np.array([1,2,3])
print("array a:",a)

array a: [1 2 3]


In [3]:
#from tuple to array
a = np.array((1,2,3))
print("array a:",a)

array a: [1 2 3]


In [8]:
#create an array with evenly spaced values
b = np.arange(0,10,2)
print("array b:",b)

array b: [0 2 4 6 8]


In [11]:
#create an array with odd spaced values
b = np.arange(0,10,3)
print("array b:",b)

array b: [0 3 6 9]


In [15]:
#create an array filled with zeroes 
d = np.zeros((2,3))
print("array d:\n",d)

array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#Evenly spaced numbers
a = np.linspace(0, 8, 5)   # 5 values between 0 and 8
print(a)

[0. 2. 4. 6. 8.]


### there are 0 to 255 pixels

In [19]:
#create an array filled with ones
e = np.ones((2,3))
print("array e :",e)

array e : [[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
e = np.ones((2,3),dtype= int)
print("array e :",e)

array e : [[1 1 1]
 [1 1 1]]


In [21]:
#create an IDENTITY matrix
f = np.eye(4)
print("identity matrix:",f)

identity matrix: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
a = np.empty((2, 3))
print(a)


[[9.54361025e-312 9.54361025e-312 9.54361025e-312]
 [9.54358120e-312 6.39831292e-315 9.54394101e-312]]


## 2. Array Manipulation Functions

In [23]:
#reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3)) #1*3 worked
print("reshaped array:",reshaped)#but 1*4 won't work

reshaped array: [[1 2 3]]


In [25]:
#flatten an array with RAVEL
f1 = np.array([[1,2],[3,4,]]) #FLATTENIG A LIST OF LIST
flattened = np.ravel(f1) 
print("flattened array:",flattened)

flattened array: [1 2 3 4]


In [10]:
a = np.array([[1, 2], [3, 4]])
b = a.flatten()
print(b)

[1 2 3 4]


In [12]:
a = np.array([[1, 2], [3, 4]])
b = a.ravel()
print(b)


[1 2 3 4]


### Flatten and ravel perform the same function
#### but flatten do not change the actual array and ravel changes the actual array

In [15]:
a = np.array([[1, 2], [3, 4]])
b = a.flatten()

b[0] = 100
print(a) #unchanged
print(b)


[[1 2]
 [3 4]]
[100   2   3   4]


In [16]:
c = a.ravel()
c[0] = 100
print(a)   # original array changes


[[100   2]
 [  3   4]]


In [11]:
# TRANSPOSE AN ARRAY
g = np.array([[1,2],[3,4]])
transposed = np.transpose(g)
print("transposeed array :\n", transposed)

transposeed array :
 [[1 3]
 [2 4]]


In [34]:
#stack array vertically
h = np.array([1,2])
j = np.array([3,4])
stacked = np.vstack ([h,j]) #stack a and b vertically
print("stacked arraya: \n",stacked)

stacked arraya: 
 [[1 2]
 [3 4]]


In [36]:
h = np.array([1,2])
j = np.array([3,4])
stacked = np.hstack ([h,j]) #stack a and b vertically
print("stacked arraya: \n",stacked)

stacked arraya: 
 [1 2 3 4]


In [21]:
#split array
a = np.array([1, 2, 3, 4, 5, 6])
b = np.split(a, 3) #split array three times
print(b)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [24]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.split(a, 2) #split array three times
print(b)


[array([1, 2, 3]), array([4, 5, 6])]


In [25]:
a = np.array([[1, 2, 3, 4]])
b = np.hsplit(a, 2)
print(b)


[array([[1, 2]]), array([[3, 4]])]


In [28]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

result = np.hsplit(a, 2)
print(result)


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [26]:
a = np.array([[1, 2], [3, 4]])
b = np.vsplit(a, 2)
print(b)


[array([[1, 2]]), array([[3, 4]])]


In [31]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

result = np.vsplit(a, 2)
print(result)


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [34]:
#hifts the element 
a = np.array([1, 2, 3, 4])
b = np.roll(a, 2)
print(b)


[3 4 1 2]


## 3.Mathematical Functions

In [38]:
#add two groups
g = np.array([1,2,3,4])
added = np.add(g,2)
print("2 added to g :",added)

2 added to g : [3 4 5 6]


In [39]:
#square each element
g = np.array([1,2,3,4])
squared = np.power (g,2)
print(squared)

[ 1  4  9 16]


In [42]:
#square root of each element
g = np.array([1,2,3,4])
square = np.sqrt(g)
print(square)

[1.         1.41421356 1.73205081 2.        ]


In [44]:
print(a1)
print(g)


[1 2 3]
[1 2 3 4]


In [45]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [49]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a)
print("dot product of a and a1:",dot_product)

dot product of a and a1: 14


### while working on dot procuct the dimension should be equal

In [18]:
#join two arrays
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a, b))
print(c)


[1 2 3 4]


## Statistical Functions

In [52]:
#mean
s = np.array ([1,2,3,4])
mean = np.mean(s)
print("mean of s:",mean)

mean of s: 2.5


In [53]:
s = np.array ([1,2,3,4])
variance = np.var(s)
print("variance of s:",variance)

variance of s: 1.25


In [56]:
#std. deviation of an array
s = np.array ([1,2,3,4])
std_dev = np.std(s)
print("standard deviation of s:", std_dev)

standard deviation of s: 1.118033988749895


In [57]:
# min element of an array
minimum = np.min(s)
print("min of s:",minimum)

min of s: 1


In [58]:
# max element of an array
max = np.max(s)
print("min of s:",max)

min of s: 4


## Random Sampling Functions

In [64]:
#3genrate random values bw 0 to 3
random_values = np.random.rand(3)
print(random_values)

[0.5488135  0.71518937 0.60276338]


### to make the same random number repeat

In [68]:
#set seed for reproducibilty]
random_values = np.random.rand(3)
np.random.seed(0)
print(random_values)

[0.5488135  0.71518937 0.60276338]


In [66]:
#genrate random integers
random_values = np.random.randint(0,10,size = 5)
print(random_values)

[2 4 7 6 8]


In [8]:
a = np.random.randn(4)
print(a)

[ 2.31084205  1.43262344 -0.39600102 -0.1768001 ]


## Boolean and logical functions

In [70]:
#check if all elements are true
logical_test = np.array([True, True, False])
all_true = np.all(logical_test)
print("all elements are true:",all_true)

all elements are true: False


In [71]:
logical_test = np.array([True, True, False])
any_true = np.any(logical_test)
print("any elements are true:",any_true)

any elements are true: True


## Set operation

In [43]:
# find unique elements
a = np.array([1, 2, 2, 3, 4, 4])
b = np.unique(a)
print(b)


[1 2 3 4]


In [42]:
#differnce of a and b
a = np.array([1, 2, 3, 4])
b = np.array([3, 4])

c = np.setdiff1d(a, b)
print(c)


[1 2]


In [72]:
#intersection of two array
set_a = np.array([1,2,3])
set_b = np.array([1,2,3])
intersection = np.intersect1d(set_a, set_b)
print("intersection of a and b:", intersection)

intersection of a and b: [1 2 3]


In [73]:
#union of two arrays
union = np.union1d(set_a, set_b)
print(union)

[1 2 3]


In [54]:
# MEMBERSHIP TEST
a = np.array([1, 2, 3, 4])
b = np.array([2, 4])

c = np.isin(a, b)
print(c)


[False  True False  True]


In [49]:
#improved membership test
a = np.array([10, 20, 30, 40])
b = np.array([20, 40])

c = np.isin(a, b)
print(c)


[False  True False  True]


In [51]:
#works element wise in array
a = np.array([1, 2, 3, 4, 5])
print(np.isin(3, a))        # True
print(np.isin([2, 7], a))   # [True False]


True
[ True False]


## Array attribute functions

In [35]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = a.view()

print(np.shares_memory(a, b))


True


In [36]:
b[0] = 100
print(a)
#changing in b affects a

[100   2   3   4]


In [37]:
c = a.copy()

print(np.shares_memory(a, c))


False


In [38]:
c[0] = 999
print(a)
# a does not change

[100   2   3   4]


In [ ]:
copied array
size of a in bytes
shared memory n.shares_memory

In [40]:
a = np.array([1, 2, 3])
print(a.itemsize)
# EACH INTEGER TAKES 8 BYTES

8


### create a 1D array of numbers from 1 to 10 and reshape it into a 2x5 array.

In [69]:
import numpy as np
a = np.arange(0,10)
b = a.reshape(2,5)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Stack two 1D arrays vertically and horizontally.

In [76]:
a = ([1,2,3,4,5])
b = ([4,5,6,7,8])
v = np.vstack((a, b))
n= np.hstack((a, b))
print(v)
print(n)
#also the dimension should be equal

[[1 2 3 4 5]
 [4 5 6 7 8]]
[1 2 3 4 5 4 5 6 7 8]


### Flatten a 2D array into 1D and then ravel it

In [84]:
a = np.array([[1,2,3],[4,5,6]])
flatten = a.flatten()
print(flatten)
raveled = a.ravel()
print(raveled)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


### Shift elements of an array cyclically by 2 positions.

In [85]:
a = np.array([1, 2, 3, 4, 5])
b = np.roll(a, 2)
print(b)


[4 5 1 2 3]


### Split a 2D array vertically and horizontally.

In [88]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

vsplit = np.vsplit(a, 2)
print( vsplit)

hsplit = np.hsplit(a, 2)
print(hsplit)


[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


### Check if elements of one array exist in another (membership test).

In [89]:
a = np.array([1,2,3,4,55,5,6])
b = np.array([3,4,4,6,3,2,22,])

check = np.isin(b,a)
print(check)

[ True  True  True  True  True  True False]


### Array attributes: ndim, shape, size, dtype, itemsize, nbytes

In [90]:
a = np.array([[1, 2, 3], [4, 5, 6]])

print("Dimensions:", a.ndim)
print("Shape:", a.shape)
print("Total elements:", a.size)
print("Data type:", a.dtype)
print("Bytes per element:", a.itemsize)
print("Total bytes:", a.nbytes)


Dimensions: 2
Shape: (2, 3)
Total elements: 6
Data type: int64
Bytes per element: 8
Total bytes: 48


### Create a 3x3 array of ones.

In [91]:
a = np.ones((3, 3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Create a 4x4 identity matrix.

In [93]:
a = np.eye(14)
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### Reshape a 1D array of 12 elements into 3x4.

In [96]:
a = np.array([1,2,3,4,56,6,4,2,21,13,1,2])
reshape = a.reshape(3,4)
print(reshape)

[[ 1  2  3  4]
 [56  6  4  2]
 [21 13  1  2]]


### Shift elements of a 1D array cyclically by 2 positions

In [97]:
a = np.array([10, 20, 30, 40, 50])
print(np.roll(a, 2))


[40 50 10 20 30]


### Split a 2D array vertically and horizontally

In [101]:
a = np.array([[1,2,3,3],[12,33,22,11]])
v = np.vsplit(a,2) #split in 2 equal parts equally
h = np.hsplit(a,2)
print("vsplit:",v)

print("hsplit:",h)

vsplit: [array([[1, 2, 3, 3]]), array([[12, 33, 22, 11]])]
hsplit: [array([[ 1,  2],
       [12, 33]]), array([[ 3,  3],
       [22, 11]])]


### Reverse a 1D array using slicing

In [102]:
a = np.array([1,2,3,4,5])
print(a[::-1])


[5 4 3 2 1]


### Add two arrays element-wise

In [104]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)


[5 7 9]


### Matrix multiplication (dot product

In [105]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a @ b)


[[19 22]
 [43 50]]
