In [1]:
import numpy as np

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]]) #outer square brackets represent array
print(arr1)                        #inner sq   br          ree      ONE ROW IN ARRAY


[[1 2 3]
 [4 5 6]]


### NumPy removes commas to make it look more like a math matrix rather than a Python list.

In [5]:
arr1[0]
#the whole first row will be shown

array([1, 2, 3])

In [7]:
arr1[1]
#the whole second row

array([4, 5, 6])

In [8]:
#arr1[row][column]
arr1[0][1]


np.int64(2)

### the row and column indexing starts from 0 as well

In [9]:
arr1[0, 1] #shortcut 
  

np.int64(2)

### Slicing keeps dimensions.and Indexing removes dimensions.

In [10]:
arr1[0, :]    #0 → “give me this one row”
              #: → “give me all columns
#whole row

array([1, 2, 3])

In [21]:
arr1[0]
#another way of whole row

array([1, 2, 3])

In [14]:
arr1[:,0]
#whole column

array([1, 4])

In [26]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr1[ :0] #empty array

array([], shape=(0, 3), dtype=int64)

In [17]:
arr1[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr1[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
print("shape",arr1.shape)
print("size",arr1.size)  #element
print("dtype",arr1.dtype)#type of element
print("n_dim",arr1.ndim) #dimension

shape (2, 3)
size 6
dtype int64
n_dim 2


create 1d and 3d array

In [36]:
darray = np.array([1,2,2,3])
print(darray)
threedarray = np.array([[12,21],[22,34],[44,32]])
print(threedarray)

[1 2 2 3]
[[12 21]
 [22 34]
 [44 32]]


In [38]:
#full array

full_array = np.full((3,2),7) # SHAPE, ELEMENT
print(full_array)

[[7 7]
 [7 7]
 [7 7]]


In [39]:
# Identity 

# all the elements will be o except diagonal elements as they will be 1
# always would be 3*3

id_array = np.eye(3)
print(id_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [40]:
# always would be square brackets
id_array = np.eye(4)
print(id_array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
# empty array
# will genrate two random values

empty_arr = np.empty(2)
print(empty_arr)


[5.43230922e-312 7.29112202e-304]


In [44]:
#evenly spaced array

print(np.arange(4))

[0 1 2 3]


In [45]:
print(np.arange(1,100,20))

[ 1 21 41 61 81]


In [46]:
#random values array in float

r_array = np.random.rand(2,3)
print(r_array)


[[0.65880854 0.51720461 0.8405091 ]
 [0.3914394  0.66489684 0.54528821]]


In [48]:
#random values array in int

r_array = np.random.rand(1,5,3)
print(r_array)


[[[0.07551618 0.74514503 0.63569264]
  [0.88158345 0.53398658 0.58963294]
  [0.07271697 0.12475548 0.85505018]
  [0.16825    0.76572359 0.52237659]
  [0.33979498 0.13361225 0.19783481]]]


## slicing for particular element

In [72]:
a = np.array ([1,3,6,5,9,8])
print(a)

[1 3 6 5 9 8]


In [73]:
print(a[0:3])

[1 3 6]


In [74]:
print(a[0:2])

[1 3]


In [75]:
print(a[ :2])

[1 3]


In [76]:
print(a[-3:]) #last three elements

[5 9 8]


In [77]:
print(a[1:4]) #middle element

[3 6 5]


In [78]:
print(a[0::2]) #stop index is not given which means go the last

[1 6 9]


In [79]:
print(a[ :: ])  #whole array

[1 3 6 5 9 8]


## in 2d array

In [4]:
import numpy as np

In [5]:
arr_2 =  np.array([[1,2,3,4,5],[6,5,7,8,9]])
print(arr_2)

[[1 2 3 4 5]
 [6 5 7 8 9]]


In [6]:
#indexing
print(arr_2[0]) #only 1st row is printed

[1 2 3 4 5]


In [7]:
print(arr_2[1][1])  #firtst row and first column element

5


In [12]:
print(arr_2[1][3])  #fiest row third column

8


## slicing - done for group of elements

In [14]:
arr_2

array([[1, 2, 3, 4, 5],
       [6, 5, 7, 8, 9]])

In [15]:
print(arr_2[1]) #its one dimension
print(arr_2[1:])#two dimension

[6 5 7 8 9]
[[6 5 7 8 9]]


In [18]:
print(arr_2[0:])
#OP IS ROW INSIDE A ROW WHICH MEANS ITS 2D

[[1 2 3 4 5]
 [6 5 7 8 9]]


In [20]:
print(arr_2[ :,1])
# first column will appear

[2 5]


In [22]:
arr3 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(arr3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Number of nested square brackets = number of dimensions
### arr3 is 2d array

In [23]:
print(arr3[0]) #0th row
print(arr3[1]) #1st row
print(arr3[2]) #2nd row

[1 2 3]
[4 5 6]
[7 8 9]


In [26]:
print(arr3[0][2])
print(arr3[1][2])
print(arr3[2][1])
print(arr3[1][0])

3
6
8
4


In [28]:
print(arr3[:,2]) #2nd colom

[3 6 9]


In [31]:
print(arr3[:,1])

[2 5 8]


In [33]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
print(arr3[::2,1]) #skipping every 2nd row and seeing ethe first colom

[2 8]


In [34]:
print(arr3[:: , 1:2]) #considering all rows and then the first colum is printed

[[2]
 [5]
 [8]]


print(arr3[:: , 0:1]) #SLICING ON ROWS

In [40]:
print(arr3[1:: , 0:1]) #SLICING ON COL

[[4]
 [7]]


In [41]:
print(arr3[1:: , 1:2]) #considering rows from 1st nd the the firt colum

[[5]
 [8]]


In [42]:
print(arr3[2:: , 1:2]) #considering only 2nd row nd first col

[[8]]


## Array reshaping and flatenning

In [43]:
a = np.array ([1,3,6,5,9,8])
print(a)

[1 3 6 5 9 8]


In [46]:
reshaped = a.reshape((6,1))
print(reshaped)

[[1]
 [3]
 [6]
 [5]
 [9]
 [8]]


In [47]:
reshaped2 = a.reshape((2,3))
print(reshaped2)

[[1 3 6]
 [5 9 8]]


In [49]:
print(reshaped2.flatten()) #changes high dimension array in 1D

[1 3 6 5 9 8]


## Araay stacking and spliting

In [ ]:
stacking - putting together in specific direction
spliting - breaking one array into smaller array

In [50]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [54]:
print(np.vstack((a,b))) #1d+1d =2d in o/p

[[1 2 3]
 [4 5 6]]


In [55]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [63]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [64]:
print(np.hsplit(c,3)) #spliting 3 col
#horizontal spliting

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [65]:
print(np.vsplit(c,2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]


## Mathematical operation in array

In [67]:
a = np.array([10,20,30,-40])
print(a)

[ 10  20  30 -40]


In [70]:
print(a +10)  #will perform all the operation on all the elements
print(a -10)
print(a *10)
print(a //10)

[ 20  30  40 -30]
[  0  10  20 -50]
[ 100  200  300 -400]
[ 1  2  3 -4]


In [77]:
b = np.array([1,3,4,5])
print(a)

[ 10  20  30 -40]


In [78]:
print(np.square(b))
print(np.sqrt(b))

[ 1  9 16 25]
[1.         1.73205081 2.         2.23606798]


In [79]:
print(a)
print(b)

[ 10  20  30 -40]
[1 3 4 5]


In [80]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b)) #both the dimension r compatible if they are equal in size

[ 11  23  34 -35]
[  9  17  26 -45]
[  10   60  120 -200]
[10.          6.66666667  7.5        -8.        ]


In [81]:
print(np.dot(a,b))  #dot product

-10


In [10]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dot(a, b)
# for 1D array

np.int64(32)

In [12]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

np.dot(A, B)
#for 2d array

array([[19, 22],
       [43, 50]])

In [83]:
print(np.transpose(a. T)) #ROW TO COL AND COL TO ROW

[ 10  20  30 -40]


In [14]:
a = np.array([1, 2, 3])
a.T
#Shape: (3,)
#Transpose has nothing to swap

array([1, 2, 3])

In [18]:
t = np.array([[1,2,3],
             [4,5,6]])
print("original")
print(t)
print("transpose")
print(t.T)

original
[[1 2 3]
 [4 5 6]]
transpose
[[1 4]
 [2 5]
 [3 6]]


## Statisctical functiom

### NumPy statistical functions reduce data into meaningful numbers by summing, averaging, or 
measuring spread — either across rows, columns, or the entire array.

In [21]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [28]:
print(np.sum(a))
print(np.sum(a, axis=1)) #ROW WISE SUM
print(np.sum(a, axis=0)) #COL WISE SUM

21
[ 6 15]
[5 7 9]


In [30]:
print(np.mean(a))
print(np.mean(a,axis = 1)) #row wise mean
print(np.mean(a,axis = 0)) #col wise mean

3.5
[2. 5.]
[2.5 3.5 4.5]


In [31]:
print(np.median(a))

3.5


In [32]:
print(np.min(a))
print(np.min(a, axis=0))
print(np.max(a))
print(np.max(a, axis=0))


1
[1 2 3]
6
[4 5 6]


In [33]:
np.ptp(a)
#range = max - min

np.int64(5)

In [34]:
print(np.median(a))
print(np.std(a)) #std. deviation
print(np.cumsum(a)) #cummalative son
print(np.argmin(a)) #index of min
print(np.argmax(a)) #index of max

3.5
1.707825127659933
[ 1  3  6 10 15 21]


## Array comparison

In [36]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [37]:
print(a == b) #element wise comparison
print(np.array_equal(a,b)) #complete array

[[False False False]
 [ True  True  True]]
False


In [38]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([15, 20, 25])

a > b


array([False, False,  True])

In [39]:
a == b


array([False,  True, False])

In [40]:
a > 20
#scaler comarison

array([False, False,  True])

## Broadcasting

In [42]:
a = np.array([1, 2, 3])
b = np.array([10])

a + b
# 10 is added to all the col
#b has one element → reused for every element in a

array([11, 12, 13])

In [43]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

a + b
#here every element of b is added to a

array([[11, 22, 33],
       [14, 25, 36]])

In [44]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
c = np.array([[10],
              [20]])

a + c
#col wise broadcasting

array([[11, 12, 13],
       [24, 25, 26]])

## Practice

## 1d array indexing

In [14]:
import numpy as np

In [12]:
#create 1d array and access elements
array = ([1,2,3,3,4,5])
array[3]

3

In [5]:
#fetch last element of array
array = ([1,2,3,3,4,5])
array[-1]

5

### slice elments form index 1 to 3

In [6]:
array = ([1,2,3,3,4,5])
array[1:4]


[2, 3, 3]

### get every second element

In [9]:
array = ([1,2,3,3,4,5])
print(array[0:7:2])
print(array[::2]) #ANOTHER WAY

[1, 3, 4]
[1, 3, 4]


### reverse an array

In [11]:
array = ([1,2,3,3,4,5])
array [ ::-1]

[5, 4, 3, 3, 2, 1]

## 2d array indexing

### create a 2d array and access item 6

In [16]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])

b[1, 2]

np.int64(6)

In [ ]:
### row slicing in 2d array

In [17]:
b[1 :]

array([[4, 5, 6]])

In [19]:
b[0 :,]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
b[0, :]

array([1, 2, 3])

In [21]:
b[1, :]

array([4, 5, 6])

### col slicing in 2d array

In [22]:
b[ :,1]

array([2, 5])

In [24]:
b[ :,2]

array([3, 6])

## 3d array indexing

### fetch elememt five

In [29]:
c = np.array([
    [[0, 1],
     [2, 3]],
    [[4, 5],
     [6, 7]]
])

c[1, 0, 1]


np.int64(5)

In [30]:
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### fetch elememt seven

In [34]:
c[1,1,1]

np.int64(7)

### how to find shaape and size of array

In [1]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
print(arr.shape) #ROW AND COL
print(arr.size)  #NO. OF ELEMENTS


(2, 2)
4


### reshaping and flatteiny array

In [7]:
 x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

## the rol and col defined must be divisble by 12 as there are 12 elemnts in total*

In [8]:
y = x.reshape(4,3)
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
y = x.reshape(2,6) 
y

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [10]:
y = x.flatten()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Reeversing

In [11]:
 x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [14]:
y = np.flip(x)
y

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

## psotional arg should be defied coz then only it world work*
x is the positional arg here**

In [16]:
y = np.flip(x,axis = 0)
y

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

### adding removing and sorting elemnets

In [18]:
 arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [19]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))


array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
np.add(1,2)

np.int64(3)

### hstack and vstack

In [28]:
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

print(np.vstack((a, b)))
print(np.hstack((a, b)))


[[1 2]
 [3 4]]
[1 2 3 4]


### append and concatenate

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])

print(np.append(a, b))


In [ ]:
print(np.concatenate((a, b)))

### argwhere and where

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(np.where(arr > 25, arr, 0))


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])
np.where(arr>10)

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])
np.where(arr>10)